### ISSUE TITLE
is this open source?

### ISSUE THREAD

**Issue by adbenitez** [adrien-gueret/number_knight#1]
hi, great game! one of my favorite entries this year! is this open source? if yes, could you please add a license file? I would like to make this game available as [webxdc](https://webxdc.org) or if you want to port it to webxdc yourself that would be great!

**Comment by adrien-gueret** [comment]
Hi @adbenitez , and thanks for your interest in "Number Knight"!
I've just added an [Apache License 2.0](https://github.com/adrien-gueret/number_knight/blob/main/LICENSE) on this project, thanks for your suggestion.

I don't know webxdc, so feel free to adapt the game as you wish. If you do so, please avoid adding the "save levels" feature, as it it tied on my personal Pinata account without any real security :D (and I may remove this account after JS13k competition).

**Comment by adbenitez** [comment]
thanks a lot! :pray: 

> If you do so, please avoid adding the "save levels" feature, as it it tied on my personal Pinata account without any real security :D (and I may remove this account after JS13k competition).

will do, webxdc games are completely sandboxed/offline with only a restricted API to interact with other members of the chat so the ported game can't use that feature anyways


closing the issue as solved! 
again, thanks a lot and good luck in the competition!
